export default interface IPool {
    name: string,
    blocksUrl: string,
    isPoolBase: boolean,
    isPoolActivlyMining: boolean,
    timeFromLastBlockMin: number,
    roundProgress: number,
    hopIndexTeoretical: number,
    hopIndexReal: number,
    hopIndexRealBuffered: number,
    hashrateGhPerSec: number,
    blockHtmlSelector: string,
    blocNumber: string;
    blockTimeMin: number,
    blockTimeHour: number,
    blockTimeDay: number,
    blockRewardHour: number,
    blockRewardDay: number,
    blockLastNumber: number,
    // userRewardPerBlock: number,
    // userRewardPerDay: number,
    // userRewardPerHour: number,
    // userRewardPerMin: number,

};